### PR TITLE
Modified

### PR DESCRIPTION
**Pull request by HJhongx**
## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [X] **Documentation Update**
- [ ] **Other (please describe)**

## Description
Add some parts of SDD.pdf(User Interface Design)section by editing SDD.tex

## Steps to Test This Pull Request
1. open NTOUClassroomBorrowing file
2. open doc
3. checkout SDD.pdf
4. find User Interface Design section 

## Expected behavior
There will be eight images on it

## Related Issue
#29

### CODE REVIEW

**Review by asas1asas200 — CHANGES_REQUESTED** [review]
The screenshot of register page is wrong.

Add some descriptions with these images.
And remember to add changelog in `版次變更紀錄`.

**Comment by asas1asas200** [comment]
Since some pages have been added in #48 , this patch should add more images.
Please checkout #48 then add these pages.

Notice that the topbar looks different now, some images must be updated.

**Comment by HJhongx** [comment]
Got it!

**Comment by asas1asas200** [comment]
Merged manually

**Pull request closed without merging**
