### PR TITLE
refactor(user): remove redundency codes

### PR DESCRIPTION
**Pull request by asas1asas200**
## Types of changes

- [ ] **Bugfix**
- [ ] **New feature**
- [x] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description

Move javascript of bootstrap from `partials/footer` to `partials/header` and remove `partials/footer` due to empty.

Remove login and register forms, it uses `users/session` now and render the form in frontend.

Resize topbar and change its style.

Redirect some empty page to `/home`.

## Steps to Test This Pull Request

Test if login and register functions work well.

## Expected behavior

Same as before.

### CODE REVIEW

**Review by Argentum11 — CHANGES_REQUESTED** [review]
Does the account management works? I've tested and the origin functionality of approving registered user isn't working, after clicking "帳號管理" in admin page, it doesn't redirect to the account management page.

**Comment by asas1asas200** [comment]
Because this PR doesn't touch there.
You can see the commit log below:

Account management page is in another branch.

**Comment by Argentum11** [comment]
Sorry, it's my fault, I didn't check the commit log. How can I see this commit log image, is it a vscode plugin or another software?

**Comment by asas1asas200** [comment]
I use [GitKraken](https://www.gitkraken.com/), you can also use another tools to see it.

Session is for RESTful url degisn, it means you are operating a session.

**Review by Argentum11 — APPROVED** [review]

**Pull request merged**
