### PR TITLE
Cherrio problem

### PR DESCRIPTION
**Pull request by Bookweight**
## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [x] **Other (Help)**

## Description
I am having a problem getting the value of name of the classroom and etc.
I was getting the "#name" and "#capacity", but the value is undefined.
Is it because the modal is not only used by one classroom or i'm getting the value from the wrong place?

npm test result:
cheerio prob 2

web page:
cheerio prob 1

code(103 to 109):
cheerio prob 3

## Steps to Test This Pull Request
run npm test.

## Expected behavior
the test case with cheerio check will fail.

### CODE REVIEW

**Comment by asas1asas200** [comment]
Because the classroom info modal is render by JavaScript, but `cheerio` is not a web browser.
You can get classroom name by get `/admin/classroom`, then get `/building/${building.name}/floor/${floor.name}/classroom/${classroom.name}`, it will return a classroom info content.

**Comment by Bookweight** [comment]
Is this right ? It passes the npm test but something felt wierd.

**Comment by Bookweight** [comment]
You mean use this to get the info? So I don't need to use cheerio?

p 1

**Comment by asas1asas200** [comment]
You need to get specific classroom info then use cheerio to check it.

**Pull request closed without merging**
